### ISSUE TITLE
Recent changes break path display.

### ISSUE THREAD

**Issue by Sneakpeakcss** [hacel/recent#21]
@dyphire 

https://github.com/hacel/recent/commit/52f64651a0f06b256743d95739ca751839435880 broke `show_paths=true` for `osc`. It only displays filename+extension, while `uosc` still shows full paths correctly:

![1](https://github.com/hacel/recent/assets/77424331/3ba56a32-5c40-4fbd-835b-bedd45068764)

![2](https://github.com/hacel/recent/assets/77424331/e0624376-b105-49f9-9817-6dac30903011)
 

Then next commit (https://github.com/hacel/recent/commit/584ac4db8bdab5d72461a89b12f2eac6cf752566) broke displaying paths for both `osc` and `uosc`.

![3](https://github.com/hacel/recent/assets/77424331/2c9c6fc0-7227-47b0-94f2-a786af7c53d8)

![4](https://github.com/hacel/recent/assets/77424331/89113501-8ade-4670-9826-de2a50d1ed7b)

And current version just crashes when using `show_paths` with default `osc`

```
[recent] 
[recent] stack traceback:
[recent] 	...op/mpv-x86_64-v3-20240531-git-481e498/scripts/recent.lua:110: in function 'get_filename'
[recent] 	...op/mpv-x86_64-v3-20240531-git-481e498/scripts/recent.lua:278: in function 'draw_list'
[recent] 	...op/mpv-x86_64-v3-20240531-git-481e498/scripts/recent.lua:393: in function 'display_list'
[recent] 	...op/mpv-x86_64-v3-20240531-git-481e498/scripts/recent.lua:444: in function 'prop'
[recent] 	mp.defaults:410: in function 'handler'
[recent] 	mp.defaults:513: in function 'call_event_handlers'
[recent] 	mp.defaults:555: in function 'dispatch_events'
[recent] 	mp.defaults:506: in function <mp.defaults:505>
[recent] 	[C]: at 0x7ff681fa4e80
[recent] 	[C]: at 0x7ff681fa3ce0
[recent] Lua error: ...op/mpv-x86_64-v3-20240531-git-481e498/scripts/recent.lua:110: bad argument #1 to 'split_path' (string expected, got nil)
```

___

I didn't check how it behaves with `mpv-menu-plugin`, but probably not any better.

**Comment by dyphire** [comment]
> @dyphire
> 
> [52f6465](https://github.com/hacel/recent/commit/52f64651a0f06b256743d95739ca751839435880) broke `show_paths=true` for `osc`. It only displays filename+extension, while `uosc` still shows full paths correctly:
> 
> Then next commit ([584ac4d](https://github.com/hacel/recent/commit/584ac4db8bdab5d72461a89b12f2eac6cf752566)) broke displaying paths for both `osc` and `uosc`.

This is wrong, if you want to show the full path you also need to set `split_paths=false`. The uosc menu in the commit (52f6465) was just done wrong and fixed in the next commit (584ac4d).
PS: Incidentally, the full path will never shown in the menu of uosc and mpv-menu-plugin, this is intentional. The full path effect is too ugly.
> 
> And current version just crashes when using `show_paths` with default `osc`
> 
> ```
> [recent] 
> [recent] stack traceback:
> [recent] 	...op/mpv-x86_64-v3-20240531-git-481e498/scripts/recent.lua:110: in function 'get_filename'
> [recent] 	...op/mpv-x86_64-v3-20240531-git-481e498/scripts/recent.lua:278: in function 'draw_list'
> [recent] 	...op/mpv-x86_64-v3-20240531-git-481e498/scripts/recent.lua:393: in function 'display_list'
> [recent] 	...op/mpv-x86_64-v3-20240531-git-481e498/scripts/recent.lua:444: in function 'prop'
> [recent] 	mp.defaults:410: in function 'handler'
> [recent] 	mp.defaults:513: in function 'call_event_handlers'
> [recent] 	mp.defaults:555: in function 'dispatch_events'
> [recent] 	mp.defaults:506: in function <mp.defaults:505>
> [recent] 	[C]: at 0x7ff681fa4e80
> [recent] 	[C]: at 0x7ff681fa3ce0
> [recent] Lua error: ...op/mpv-x86_64-v3-20240531-git-481e498/scripts/recent.lua:110: bad argument #1 to 'split_path' (string expected, got nil)
> ```

fixed by https://github.com/hacel/recent/commit/a810bc3cbd3ae4021913a6332433c5af8038998a
