### ISSUE TITLE
The ‘list_show_amount’ option in the recent.conf file does not work

### ISSUE THREAD

**Issue by CNhjx** [hacel/recent#22]
list_show_amount=10:
![image](https://github.com/hacel/recent/assets/57735696/b03e5e46-4298-4b71-84c0-3177860e95db)
list_show_amount=20:
![image](https://github.com/hacel/recent/assets/57735696/48ffaa0a-f174-426c-b0da-0a60a7658db2)
list_show_amount=1:
![image](https://github.com/hacel/recent/assets/57735696/6e0d5f32-ee89-447a-8ec9-2f1f109c4cdb)
It always shows ten records.

**Comment by dyphire** [comment]
https://github.com/hacel/recent/blob/2c5112b1939afae0c217499f1a5478a6eb31361b/recent.lua#L39-L40

As mentioned in the code comments, this option only applies to the integrated submenus in uosc and mpv-menu-plugin.

**Comment by CNhjx** [comment]
My bad. I was careless.
