### ISSUE TITLE
[feature request] Adding pages or scrolling to be able to see more recents.

### ISSUE THREAD

**Issue by Reinbowsaur** [hacel/recent#9]
Would be nice if we could view more recents. Best you can do at the moment is change the font size smaller so you can view more on the screen at once.
 
https://github.com/NurioHin/mpv-bookmarker does this well for example. I don't expect it to be easy but if it could be implemented in some way it'd be great either by pages, or scrolling.

**Comment by hacel** [comment]
Not sure what you mean. You can scroll down through all the files.

**Comment by Reinbowsaur** [comment]
I feel very dumb. I didn't notice this behavior when scrolling down because of the way I modified your script, which changed the minimum list selection for it to start visually scrolling down, and I also had the list flooding off screen. 

Sorry for the trouble! And thankyou for the script!
